### ISSUE TITLE
Cannot migrate MRs with attachments

### ISSUE THREAD

**Issue by mike-potter** [piceaTech/node-gitlab-2-github#103]
Even after setting up an S3 bucket, trying to migrate a MR that has an attachment gives the following error:
```
Could not download attachment FILENAME.png
Error: params.Body is required
    at ManagedUpload.validateBody (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:271:13)
    at ManagedUpload.configure (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:123:10)
    at new ManagedUpload (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:95:10)
    at features.constructor.upload (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/services/s3.js:1383:20)
    at Response.<anonymous> (/Users/username/Projects/node-gitlab-2-github/src/utils.ts:75:16)
    at Request.<anonymous> (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:369:18)
    at Request.callListeners (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/username/Projects/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:22:10) {
```
And the resulting PR in Github is not created.

Is there a way to still migrate the MR->PR and just not include the attachment?

**Comment by mdbenito** [comment]
This is a problem with the download of the attachment. #117 skips files with this issue, albeit not very elegantly (silently ignores them)

**Comment by mdbenito** [comment]
To be more precise, the problem can be either a download issue or a permissions issue. For the former there is the "fix" of silently ignoring the failed download. For the latter, #117 introduces the possibility to add a browser session cookie to the settings which then allows this script to download arbitrary attachments. This is a workaround for GitLab's API lack of endpoint to download attachment
