### ISSUE TITLE
Getting SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by Aditgaur** [piceaTech/node-gitlab-2-github#11]
Hi Team,
I am getting below error while migrating from Gitlab CE to github enterprise.

undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o in JSON at position 1
    at Object.parse (native)
    at /home/aditgaur/puppet-agent-automation.git/node-gitlab-2-github/node_modules/gitlab/lib/ApiBaseHTTP.js:88:42
    at _Class.wrap_response (/home/aditgaur/puppet-agent-automation.git/node-gitlab-2-github/node_modules/slumber/lib/API.js:192:18)
    at _Class.wrap_response (/home/aditgaur/puppet-agent-automation.git/node-gitlab-2-github/node_modules/slumber/lib/API.js:4:59)
    at Request._callback (/home/aditgaur/puppet-agent-automation.git/node-gitlab-2-github/node_modules/slumber/lib/API.js:215:26)
    at Request.self.callback (/home/aditgaur/puppet-agent-automation.git/node-gitlab-2-github/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/aditgaur/puppet-agent-automation.git/node-gitlab-2-github/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)

**Comment by edno** [comment]
Just try to debug your `settings.json` file with a JSON parser. Best guess it is an invisible char (or LRCF issue)

**Comment by spruce** [comment]
Have you found the Problem. Sorry I somehow missed the notification. uups.

**Comment by chraibi** [comment]
some news here?

**Comment by MJochim** [comment]
I encountered the same error when trying to run the software without a Gitlab token (I tried that out of curiosity). After creating a gitlab access token and putting it in settings.json, everything worked fine. Thanks for your software :-)

**Comment by spruce** [comment]
@MJochim you also got the error with the same error message? Than  I would check that inside the application. @chraibi Have you set a token?

**Comment by MJochim** [comment]
Yep, same message, same stack trace.

**Steps to reproduce**

1. git clone, npm i, cp sample_settings.json settings.json
2. Replace the value of gitlab.url in settings.json (use e.g. https://gitlab.lrz.de/ or http://www.google.de/)
3. node index.js

**Result**

If you use an actual gitlab instance in step 2, you get the message described in this issue.
If you use some other URL (e.g. Google), you get a different message.

**Comment**

This needs fixing in the gitlab package and has actually been documented at https://github.com/node-gitlab/node-gitlab/issues/149.

However some changes in this codebase might also be in order. Try making the change I suggested upstream, repeat the *steps to reproduce* and you will end up with another error:

TypeError: projects.sort is not a function

Something like ```Array.isArray(projects)``` inside the callback function on line 16 might do the trick.

**Comment by spruce** [comment]
Can you open a new issue with that text? So I can better track it and we don't get on the nerves of the others. Thanks for the repro that helps a lot
