### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by KodaCHC** [piceaTech/node-gitlab-2-github#132]
I have used an older version of this project until today. Since I always got into a rate limit (Not the second rate limit - after 6 hours break and only 30 issues) I downloaded the newest version today and adjusted the settings.ts.

But when I run "npm run start" no issues are imported at the end. Here is the last error message

```
Migrating issue #124 ('CUT_CUT_CUT')...
        ...ERROR while migrating issue #124.
DEBUG:
 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at GithubHelper.<anonymous> (/root/node-gitlab-2-github/src/githubHelper.ts:1143:43)
    at step (/root/node-gitlab-2-github/src/githubHelper.ts:52:23)
    at Object.next (/root/node-gitlab-2-github/src/githubHelper.ts:33:53)
    at /root/node-gitlab-2-github/src/githubHelper.ts:27:71
    at new Promise (<anonymous>)
    at __awaiter (/root/node-gitlab-2-github/src/githubHelper.ts:23:12)
    at GithubHelper.convertIssuesAndComments (/root/node-gitlab-2-github/src/githubHelper.ts:1310:16)
    at GithubHelper.<anonymous> (/root/node-gitlab-2-github/src/githubHelper.ts:432:20)
    at step (/root/node-gitlab-2-github/src/githubHelper.ts:52:23)
        -> creating a replacement issue...
        ...ERROR: Could not create replacement issue either!
DONE creating issues.

        Statistics:
        Total nr. of issues: 124
        Nr. of used placeholder issues: 0
        Nr. of used replacement issues: 0
        Nr. of issue migration fails: 124


Transfer complete!
```

**Comment by 4x0v7** [comment]
Just ran into this too. What version were you using that worked @KodaCHC ?

**Comment by 4x0v7** [comment]
Solved it. I hadn't set `usermap` and `projectmap`
All migrated!

**Comment by spruce** [comment]
@KodaCHC Can You see whether setting `usermap` und `projectmap` fixes it for you as well?
