### ISSUE TITLE
No existing release for this tag on github

### ISSUE THREAD

**Issue by mochadwi** [piceaTech/node-gitlab-2-github#139]
Creating release: !1.23.0 RC03 - v1.23.0-rc03

<details>
<summary>Click to see the logs</summary>
```
Could not create release on github
RequestError [HttpError]: Validation Failed: {"resource":"Release","code":"custom","message":"Repository is empty."}
    at ~/Documents/<project>/node-gitlab-2-github/node_modules/@octokit/request/dist-src/fetch-wrapper.js:68:27
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Job.doExecute (~/Documents/node-gitlab-2-github/node_modules/bottleneck/light.js:405:18) {
  status: 422,
  response: {
    url: 'https://api.github.com/repos/<org>/<repo>/releases',
    status: 422,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-length': '198',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sun, 15 May 2022 04:25:58 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-oauth-scopes': 'repo',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; param=golden-comet-preview; format=json',
      'x-github-request-id': '2645:53D0:104C50:119851:628080D6',
      'x-oauth-scopes': 'admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, delete:packages, delete_repo, gist, notifications, repo, user, workflow, write:discussion, write:packages',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4767',
      'x-ratelimit-reset': '1652589446',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '233',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Validation Failed',
      errors: [Array],
      documentation_url: 'https://docs.github.com/rest/reference/repos#create-a-release'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/<org>/<repo>/releases',
    headers: {
      accept: 'application/vnd.github.golden-comet-preview+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.5.1 Node.js/15.8.0 (darwin; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"tag_name":"v1.23.0-rc03","name":"1.23.0 RC03","body":"# CHANGELOG\\n\\n1. TODO !1574\\n\\n## Bugfix\\n\\n1. -\\n\\n## Impact\\n\\n1. -"}',
    request: { hook: [Function: bound bound register] }
  }
}
```

</details>

Somehow unable to create release, does it required to manually create the release first(?) before the migration?

**Comment by krah034** [comment]
I did not use gitlab-2-github yet. But I am planning to - that's why I am currently browsing through the issues.

I guess you did not mirror your GitLab repo on GitHub first. The message also says "Repository is empty".
