### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by colenr** [piceaTech/node-gitlab-2-github#144]
Hello, I'm attempting to migrate an old GitLab server (GitLab 7.10.4 and GitLab API v3) to GitHub and am running into an issue getting the transfer to work properly as I continually am getting this:

 ```
$ npm run start

> gitlab-2-github@0.1.5 start
> node node_modules/ts-node/dist/bin.js ./src/index.ts

==================================
Transferring Description
==================================
Error during transfer:
TypeError: Cannot read properties of undefined (reading 'replace')
    at GithubHelper.<anonymous> (/mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/githubHelper.ts:320:32)
    at step (/mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/githubHelper.ts:52:23)
    at Object.next (/mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/githubHelper.ts:33:53)
    at /mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/githubHelper.ts:27:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/githubHelper.ts:23:12)
    at GithubHelper.updateRepositoryDescription (/mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/githubHelper.ts:374:16)
    at /mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/index.ts:240:22
    at step (/mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/index.ts:52:23)
    at Object.next (/mnt/nfs/dubbletrubble/DCEG/CGR/CoreServices/gitMigration/node-gitlab-2-github/src/index.ts:33:53)


Transfer complete!
```
Settings file is here:

```
$ cat settings.ts
import Settings from './src/settings';

export default {
  gitlab: {
    url: 'http://10.133.130.114',
    token: '<token>',
    projectId: 124,
    sessionCookie: null,
  },
  github: {
    // baseUrl: 'https://github.mycompany.com:123/etc',
    // apiUrl: 'https//api.github.mycompany.com',
    owner: 'NCI-CGR',
    token: '<token>,
    token_owner: 'colenr',
    repo: 'merge-pipeline',
    recreateRepo: false,
  },
  s3: {
    accessKeyId: '{{accessKeyId}}',
    secretAccessKey: '{{secretAccessKey}}',
    bucket: 'my-gitlab-bucket',
  },
  usermap: {
    'username.gitlab.1': 'username.github.1',
    'username.gitlab.2': 'username.github.2',
  },
  projectmap: {
    'gitlabgroup/projectname.1': 'GitHubOrg/projectname.1',
    'gitlabgroup/projectname.2': 'GitHubOrg/projectname.2',
  },
  conversion: {
    useLowerCaseLabels: true,
  },
  transfer: {
    description: true,
    milestones: true,
    labels: true,
    issues: true,
    mergeRequests: true,
    releases: true,
  },
  debug: false,
  useIssueImportAPI: true,
  usePlaceholderMilestonesForMissingMilestones: true,
  usePlaceholderIssuesForMissingIssues: true,
  useReplacementIssuesForCreationFails: true,
  useIssuesForAllMergeRequests: false,
  filterByLabel: null,
  skipMergeRequestStates: [],
  skipMatchingComments: [],
  mergeRequests: {
    logFile: './merge-requests.json',
    log: false,
  },
} as Settings;
```

I've confirmed I can access the project via that ID from the API and with the used token.  I've also successfully used this code and installation to migrate some GitLab.com repos to GitHub so I'm reasonably confident I have everything configured properly.  

Can anyone point me to what might be going on or how to fix it?

**Comment by dandrzejewski** [comment]
Set a project description on your GitLab project.

**Comment by spruce** [comment]
Did that help? But I also think we should not crash on a missing description in gitlab

**Comment by colenr** [comment]
I honestly can't speak to whether that would work or not.  We were on a pretty tight schedule and I wound up doing things a bit more manually and the server has now been shutdown.  Thank you for the suggestion and I hope it helps someone else.

**Comment by Revolt9k** [comment]
Add description to gitLab project **does** help with this issue.
