### ISSUE TITLE
404 when trying to migrate merge requests to github issues

### ISSUE THREAD

**Issue by dotspec** [piceaTech/node-gitlab-2-github#150]
This is vexing me as it worked on a repo I was testing with last week and now seems to be broken no matter what I try.  I'm trying to migrate a bunch of repos to github and when it gets to the part of converting MRs without branches to issues every one returns 404 unless the issue already exists then it returns as expected.  Here are the details of the response.

RequestError [HttpError]: Not Found
    at /Users/dgordon/src/node-gitlab-2-github/node_modules/@octokit/request/dist-src/fetch-wrapper.js:68:27
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (/Users/dgordon/src/node-gitlab-2-github/node_modules/bottleneck/light.js:405:18) {
  status: 404,
  response: {
    url: 'https://api.github.com/repos/OurGithubOrg/the-repo/issues/',
    status: 404,

    
    data: {
      message: 'Not Found',
      documentation_url: 'https://docs.github.com/rest'
    }

While I was troubleshooting things I did notice that including a trailing forward-slash on the url will produce that same error, however dropping it succeeds.  I feel like I'm doing something wrong here but I've gone through the process a number of times now, reissued tokens, recreated repos, triple-checked my settings.ts and everything looks good there.  Any thoughts?  I'm happy to include my particular settings if it'll help.

**Comment by dotspec** [comment]
I figured it out.  I think it's this [this](https://github.com/piceaTech/node-gitlab-2-github/issues/133).  The readme makes it sound like it won't make any requests to github but the logging sure makes it look like it is.  Anyway, closing.
