### ISSUE TITLE
undefined:1

### ISSUE THREAD

**Issue by chraibi** [piceaTech/node-gitlab-2-github#16]
I get the following errors 

```
undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o
    at Object.parse (native)
    at /Users/chraibi/Workspace/node-gitlab-2-github/node_modules/gitlab/lib/ApiBaseHTTP.js:88:42
    at _Class.wrap_response (/Users/chraibi/Workspace/node-gitlab-2-github/node_modules/gitlab/node_modules/slumber/lib/API.js:192:18)
    at _Class.wrap_response (/Users/chraibi/Workspace/node-gitlab-2-github/node_modules/gitlab/node_modules/slumber/lib/API.js:4:59)
    at Request._callback (/Users/chraibi/Workspace/node-gitlab-2-github/node_modules/gitlab/node_modules/slumber/lib/API.js:215:26)
    at Request.self.callback (/Users/chraibi/Workspace/node-gitlab-2-github/node_modules/gitlab/node_modules/slumber/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/chraibi/Workspace/node-gitlab-2-github/node_modules/gitlab/node_modules/slumber/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
```

This is my settings-file

```
{
  "gitlab": {
    "url": "http://gitlab.version.fz-juelich.de/",
    "token": "{{TOKEN}}",
    "projectID": null
  },
  "github": {
    "url": "api.github.com",
    "pathPrefix": "JuPedSim",
    "owner": "{{JuPedSim}}",
    "username": "{{chraibi}}",
    "password": "{{pw}}",
    "repo": "{{jpscore}}"
  },
  "usermap": {
    "chraibi1": "chraibi",
      "graf2": "ArneGraf",
      "andresen1": "Erik-Andresen"
  },
  "projectmap": {
    "JuPedSim/jpscore": "JuPedSim/jpscore"
  }
}
```

I validated the file. Any idea what went wrong?

**Comment by spruce** [comment]
Have you looked into issue #11 ? Sounds like the same thing

**Comment by chraibi** [comment]
Yes it looks very similar, however there is no solution there. 
I was also thinking something must be wrong with the setting file. I checked it 
with this [validator](https://github.com/zaach/jsonlint). It does not give any error. 

I looked at the white spaces but does not see anything suspicious.

**Comment by spruce** [comment]
I just noticed. That your stacktrace actually points to one of the dependencies: gitlab.

**Comment by spruce** [comment]
See: https://github.com/node-gitlab/node-gitlab/issues/149

**Comment by lsoltero35** [comment]
What @MJochim proposed on node-gitlab/node-gitlab#149 worked for me as a workaround.

**Comment by spruce** [comment]
I got the PR merged but sadly there is still no new release on npm.

**Comment by spruce** [comment]
Still no new version

**Comment by spruce** [comment]
With 5f506a2ba544cb6e11618928c4e080baf9af2fac I upgraded to a maintained version of the gitlab module. Can you check if it works?

**Comment by spruce** [comment]
I'm closing this because there is no reaction. Please feel free to reopen if it still doesn't work.

**Comment by chraibi** [comment]
Thanks for your efforts and sorry for missing this. 
I don't have this error anymore but hit another one :-)
