### ISSUE TITLE
RequestError [HttpError]: request to https://api.github.com/repos/{owner}/{repo} failed, reason: connect ETIMEDOUT

### ISSUE THREAD

**Issue by 2no553** [piceaTech/node-gitlab-2-github#201]
When I try to run npm run start targeting a GitHub organization in a proxy environment, I encounter the following error and am unsure how to resolve it. If there are any workarounds, could you please advise?

```
Could not access the GitHub repo
RequestError [HttpError]: request to https://api.github.com/repos/{owner}/{repo} failed, reason: connect ETIMEDOUT IP:443
    at ~\node-gitlab-2-github\node_modules\@octokit\request\dist-src\fetch-wrapper.js:92:15
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Job.doExecute (~\node-gitlab-2-github\node_modules\bottleneck\light.js:405:18) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/{owner}/{repo}',
    headers: {
      accept: 'application/vnd.github.golden-comet-preview+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.5.1 Node.js/20.10.0 (win32; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

The HTTP_PROXY setting has been configured in the Windows system environment variables and .gitconfig

**Comment by spruce** [comment]
I hope you found a solution for the problem, as I'm really late to answer. Could you document it or even create a PR which implements that? thanks
