### ISSUE TITLE
RequestError [HttpError]: request to https://api.github.com/repos/XXXXXXXX failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by Hikaru-13915** [piceaTech/node-gitlab-2-github#203]
The codes below are outputs of `docker run node-gitlab-2-github:latest`

```bash
> gitlab-2-github@0.1.5 start
> node node_modules/ts-node/dist/bin.js ./src/index.ts

(node:18) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Could not access GitHub repo
RequestError [HttpError]: request to https://api.github.com/repos/XXXXXXXXX failed, reason: read ECONNRESET
    at /app/node_modules/@octokit/request/dist-src/fetch-wrapper.js:92:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18) {
  status: 500,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/XXXXXXXXXXXX',
    headers: {
      accept: 'application/vnd.github.golden-comet-preview+json',
      'user-agent': 'octokit-rest.js/18.12.0 octokit-core.js/3.5.1 Node.js/16.20.2 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  }
}
```

**Comment by spruce** [comment]
Sorry for the long delay. This project currently has a low priority for me.

It looks like it is a network problem and not related to this project. Did it work after some time?
