### ISSUE TITLE
Cannot read property 'body' of null

### ISSUE THREAD

**Issue by JoshuaGarrison27** [piceaTech/node-gitlab-2-github#23]
I have a private repo that I am trying to move from GitLab to Github but I keep getting this error message when I try to run the project.

**Replaced key/password info for privacy**
```
PS D:\node-gitlab-2-github> node index.js
{ gitlab:
   { url: 'https://gitlab.com/',
     token: 'MyToken',
     projectID: 644417 },
  github:
   { url: 'api.github.com',
     pathPrefix: '',
     owner: 'JoshuaGarrison27',
     username: 'JoshuaGarrison27',
     password: 'Password',
     repo: 'Project1' },
  usermap: { JoshuaGarrison27: 'JoshuaGarrison27' },
  projectmap: { 'JoshuaGarrison27/Project1': 'JoshuaGarrison27/Project1' } }




D:\node-gitlab-2-github\node_modules\gitlab\lib\ApiBaseHTTP.js:88
              return fn(err, ret || JSON.parse(response.body).message);
                                            ^

TypeError: Cannot read property 'body' of null
    at D:\node-gitlab-2-github\node_modules\gitlab\lib\ApiBaseHTTP.js:88:45
    at _Class.wrap_response (D:\node-gitlab-2-github\node_modules\slumber\lib\API.js:192:18)
    at _Class.wrap_response (D:\node-gitlab-2-github\node_modules\slumber\lib\API.js:4:59)
    at Request._callback (D:\node-gitlab-2-github\node_modules\slumber\lib\API.js:210:26)
    at self.callback (D:\node-gitlab-2-github\node_modules\request\request.js:188:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (D:\node-gitlab-2-github\node_modules\request\request.js:884:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
```

**Comment by spruce** [comment]
Hey,
this seems to be a problem with some of your connecting params. As this doesn't occur inside node-gitlab-2-github. Do you have any more log output?

**Comment by spruce** [comment]
On another note have you checked this issue out: https://github.com/node-gitlab/node-gitlab/issues/149

**Comment by JoshuaGarrison27** [comment]
This issue was caused by the proxy used my our company. I tried it on an external connection and it worked. I had to delete the 'bug'  label in my new GitHub repo because it was throwing an error of a duplicate label in this script. However after I did that, it works perfectly. Thank you! Sorry for any wasted time.
