### ISSUE TITLE
Unexpected Token Function

### ISSUE THREAD

**Issue by adcox** [piceaTech/node-gitlab-2-github#42]
I'm getting the following error when I run the `node index.js` command:

```
/home/.../node-gitlab-2-github/index.js:67
async function listProjects() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

For context, I'm running Ubuntu 16.04.6 and I installed the `npm`, `nodejs`, and `nodejs-legacy` packages via the `apt` interface. Is this a version issue? I checked the versions on those packages: `nodejs` is v4.2.6 and `npm` is version 3.5.2.

**Comment by adcox** [comment]
Turns out it was a version issue. I had to override the default Ubuntu package for `nodejs` and install a new version (I chose 11.x). It all seems to be running now!
