### ISSUE TITLE
Could not create milestone HttpError: 'description' cannot be null

### ISSUE THREAD

**Issue by archon810** [piceaTech/node-gitlab-2-github#68]
```
==================================
Transferring Milestones
==================================
Creating: 1.0
Creating: 2.0
Could not create milestone 2.0
{ HttpError: 'description' cannot be null
    at values.forEach (workspace/node-gitlab-2-github/node_modules/@octokit/rest/plugins/validate/validate.js:60:15)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach.parameterName (workspace/node-gitlab-2-github/node_modules/@octokit/rest/plugins/validate/validate.js:38:12)
    at Array.forEach (<anonymous>)
    at validate (workspace/node-gitlab-2-github/node_modules/@octokit/rest/plugins/validate/validate.js:16:23)
  name: 'HttpError',
  status: 400,
  headers: undefined,
  request: undefined }
Creating: 1.1
Creating: 1.2
```

**Comment by spruce** [comment]
It seems the description of your milestone 2.0 is empty / null. Is that correct? If so we should create a fallback for when the milestone desc is empty.

**Comment by archon810** [comment]
Actually, all of the descriptions are empty on GL's side, so I'm not sure why it only picked on `2.0`.

**Comment by spruce** [comment]
Ok. This then is clearly a bug. Care to fix it and create a PR?
