### ISSUE TITLE
Issues/MRs migration fails with TypeError: body.matchAll is not a function error 

### ISSUE THREAD

**Issue by ikeyfo** [piceaTech/node-gitlab-2-github#77]
Hi :wave:   
I am having an issue with migrating issues and merge requests (error below). However labels and milestones were migrated ok and correctly.   

It fails with the following error:   
for issue:   
```
DEBUG:
 TypeError: body.matchAll is not a function
    at /home/nikolay/projects/node-gitlab-2-github/src/utils.ts:45:24
    at step (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:52:23)
    at Object.next (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:33:53)
    at /home/nikolay/projects/node-gitlab-2-github/src/utils.ts:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:23:12)
    at Object.exports.migrateAttachments (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:36:132)
    at GithubHelper.<anonymous> (/home/nikolay/projects/node-gitlab-2-github/src/githubHelper.ts:817:38)
    at step (/home/nikolay/projects/node-gitlab-2-github/src/githubHelper.ts:52:23)
    at Object.next (/home/nikolay/projects/node-gitlab-2-github/src/githubHelper.ts:33:53)
        -> creating a replacement issue...
        ...ERROR: Could not create replacement issue either!

Statistics:
        Total nr. of issues: 3395
        Nr. of used placeholder issues: 1
        Nr. of used replacement issues: 0
        Nr. of issue migration fails: 3395
```

for MRs it's the same  
```
Could not create pull request: !1 - WIP: Resolve "Cancel for job without applications"
TypeError: body.matchAll is not a function
    at /home/nikolay/projects/node-gitlab-2-github/src/utils.ts:45:24
    at step (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:52:23)
    at Object.next (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:33:53)
    at /home/nikolay/projects/node-gitlab-2-github/src/utils.ts:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:23:12)
    at Object.exports.migrateAttachments (/home/nikolay/projects/node-gitlab-2-github/src/utils.ts:36:132)
    at GithubHelper.<anonymous> (/home/nikolay/projects/node-gitlab-2-github/src/githubHelper.ts:817:38)
    at step (/home/nikolay/projects/node-gitlab-2-github/src/githubHelper.ts:52:23)
    at Object.next (/home/nikolay/projects/node-gitlab-2-github/src/githubHelper.ts:33:53)
```  

Did I miss something during configuration in the `settings.ts` file or it's something completely else?

**Comment by ashwinma** [comment]
I stumbled upon the exact same error. Install nodejs v12 or higher and the error goes away.

**Comment by spruce** [comment]
@ikeyfo which node version did you use? can you confirm that it migrates successfully when using node > v12?

**Comment by ikeyfo** [comment]
@spruce yep, I were using 10.14. After upgrade everything works fine
Thanks @ashwinma :)

**Comment by Sciss** [comment]
Have the same issue, node is v10 on Debian stable. Please put this prominently in the README. Thank you
