### ISSUE TITLE
Cannot read property 'toString' of undefined while fetching GitLab projects

### ISSUE THREAD

**Issue by aleksey-katerov** [piceaTech/node-gitlab-2-github#78]
Hi, I am trying to migrate some our projects from our inner enterprise GitLab to GitHub and get following:

An Error occured while fetching all GitLab projects:
TypeError: Cannot read property 'toString' of undefined
    at GitlabHelper.<anonymous> (/tmp/gittest/node-gitlab-2-github/src/gitlabHel                                                                             per.ts:39:26)
    at step (/tmp/gittest/node-gitlab-2-github/src/gitlabHelper.ts:33:23)
    at Object.next (/tmp/gittest/node-gitlab-2-github/src/gitlabHelper.ts:14:53)
    at fulfilled (/tmp/gittest/node-gitlab-2-github/src/gitlabHelper.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Any help is appreciated.

Settings are:
import Settings from './src/settings';

export default {
  gitlab: {
    url: '<Gitlab_root>/<GitLab_subgroup>',
    token: 'migrate:<token>',
    projectId: null,
  },
  github: {
    baseUrl: 'api.github.com',
    owner: '<username>',
    token: '<tocken>',
    repo: '<repo_name>',
  },
  usermap: {
    ...
  },
  projectmap: {
    '<project_name>': '<namespace>/<project_name>',
  },
  conversion: {
    useLowerCaseLabels: true,
  },
  debug: false,
  usePlaceholderIssuesForMissingIssues: true,
  useReplacementIssuesForCreationFails: true,
  useIssuesForAllMergeRequests: false,
  skipMatchingComments: [],
  mergeRequests: {
    logFile: './merge-requests.json',
    log: false,
  },
}

**Comment by spruce** [comment]
@aleksey-katerov it seems your project has no id it can print. (only toString in `gitlabHelper` I could find)

I think you need to remove the gitlab subgroup.
