### ISSUE TITLE
Errors while uploading to S3 bucket

### ISSUE THREAD

**Issue by ajRiverav** [piceaTech/node-gitlab-2-github#88]
Got this error while migrating issue data: 

```
Migrating issue #5 ('some issue')...
Could not download attachment #/uploads/<some uuid>/image.png.
	...ERROR while migrating issue #5.:
DEBUG:
 Error: params.Body is required
    at ManagedUpload.validateBody (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:271:13)
    at ManagedUpload.configure (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:123:10)
    at new ManagedUpload (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/s3/managed_upload.js:95:10)
    at features.constructor.upload (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/services/s3.js:1383:20)
    at Response.<anonymous> (/Users/*/*/node-gitlab-2-github/src/utils.ts:75:16)
    at Request.<anonymous> (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:369:18)
    at Request.callListeners (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit /Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/Users/*/*/node-gitlab-2-github/node_modules/aws-sdk/lib/request.js:22:10) {
  code: 'Error',
  time: 2021-01-18T15:51:28.783Z
}
	-> creating a replacement issue...
	Migrating issue comments...
	...no issue comments available, nothing to migrate.
	...DONE.
	
```

When observing the S3 bucket, I do see objects (images) being created.

**Comment by ajRiverav** [comment]
closing. This was solved by ensuring proper write permissions, as described in readme. https://docs.aws.amazon.com/AmazonS3/latest/dev/example-policies-s3.html#iam-policy-ex0
